### ISSUE TITLE
Counts of failed checks in the db do not match contessa counts

### ISSUE THREAD

**Issue by RadkaMeres** [kiwicom/contessa#28]
Right now counts of ** data quality check** dont match the actual count of failed data checks in main table for data.

Based on a talk with you there is some uniqueness check needed over unique identificator, if the identificator has been checked yet in case it gets updated again.

**Comment by maroshmka** [comment]
I see 2 possible features that both should solve your problem:

1. **Uniqueness** - All rows would be checked only once based on unique cols. E.g. if the same bid gets updated it wont be included in next check. Meaning it would check only created rows.

2. **Date Filter** - Argument that would allow to filter based on date. E.g. do quality checks only on rows that has fields created/updated bigger than last 10 days.

Both should probably be implemented on rule-level and extended to QualityCheck level if needed. We'll try to include one of them in todays planning.

**Comment by Linzee** [comment]
Regarding number 1.: which version of the row checks would we keep? It makes most sense to keep the last one as it represents actual version of data in database, but it is not trivial to implement. For example we would have to decrement result some previous check in case it failed before and now it is correct.

Also there are multiple reasons why we check rows more than once:
- row is updated because data changed
- row is recalculated because it falls into "lshift" - interval we process twice just in case to prevent problems with database delays

**Comment by RadkaMeres** [comment]
Regarding: _Also there are multiple reasons why we check rows more than once:_
How about in case the bid would be updated within the range of the current checked day the last updated bid would be kept?

**Comment by maroshmka** [comment]
hey guys, I believe that the date filter should partially solve some of the issues. If you define check, e.g. to check last day (off load, not on-load), you should get the true image of db state from yesterday. 

For the aggregated results, e.g. by week, the uniqueness is nots solved. As @Linzee mentioned, its not trivial to solve. We will try to design some solution for this and post here proposal.

**Comment by dee-gmiterko** [comment]
date filtering was implemented in https://github.com/kiwicom/contessa/commit/ccba9fa206000ecbaa0b8a6bd03a4cb056e0f53b
